# Generated by Django 4.1.3 on 2022-11-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=20)),
                ('item_color', models.CharField(max_length=10)),
                ('item_brand', models.CharField(max_length=30)),
                ('item_condition', models.CharField(max_length=10)),
                ('item_material', models.CharField(max_length=20)),
                ('item_price', models.IntegerField()),
                ('listing_date', models.DateTimeField(verbose_name='date listed')),
            ],
        ),
    ]
